version: '2'

services:
  web:
    image: fraunhoferiosb/ogcapisimple:latest
    environment:
      - todo=todo
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=ogcapisimple
      - POSTGRES_USER=ogcapisimple
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data
volumes:
    postgis_volume:
